#!/bin/bash

green='\033[0;32m'
clear='\033[0m'

printf "${green}Reloading BIOS...\n${clear}"
cd ..
cp ../extra/dss/bios/* ./dss/bios/
./dasm dss/bios/entry.dss -o dragon/bios.bin -D
cp dragon/bios.bin ../extra/dragon/bios.bin
