#!/bin/bash

green='\033[0;32m'
clear='\033[0m'

printf "\n${green}Compiling Drake...\n${clear}"
cd ..
cp ../extra/dss/drake/* ./dss/drake/

printf "\n${green}1) loader.dss\n${clear}"
./dasm dss/drake/loader.dss -o dragon/drake_loader.bin -D
./dtools load-binary dragon/disk1.dr dragon/drake_loader.bin 0x00000000

printf "\n${green}2) bootsector.dss\n${clear}"
./dasm dss/drake/bootsector.dss -o dragon/drake_bootsector.bin -D	
./dtools load-binary dragon/disk1.dr dragon/drake_bootsector.bin 0x00000400

printf "\n"


cp dragon/disk1.dr ../extra/dragon/disk1.dr
rm dragon/drake_loader.bin
rm dragon/drake_bootsector.bin
