#!/bin/bash

green='\033[0;32m'
clear='\033[0m'

printf "${green}\n============================================[ Building Application ]============================================\n\n${clear}"
\cp -r ../extra/* ./
if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    make
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    mingw32-make.exe
fi
printf "${green}\n=================================================================================================================\n\n"