#!/bin/bash

green='\033[0;32m'
clear='\033[0m'

printf "${green}\n============================================[ Building Application ]============================================\n\n${clear}"
\cp -r ../extra/* ./
if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    make
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    mingw32-make.exe
fi
printf "${green}\n=================================================================================================================\n\n"
if [ $? -eq 0 ]; then
    cd scripts
    /bin/bash ./bios_flash
    cp ../dss/bios_api.dss ../../extra/dss/bios_api.dss
    /bin/bash ./load_mbr
    cd ..
    printf "${green}Compiling Test Program...\n"
    ./dasm dss/activeTest.dss -o activeTest.bin --extmov --extalu --save-disassembly disassembly/activeTest.dds --verbose
    printf "\n${green}Running Application...\n\n${clear}"
    ./dtools load-binary dragon/disk1.dr activeTest.bin 0x00000400
    ./dvm config/testMachine.dvm
    # ./dvm config/testMachine.dvm --force-load activeTest.bin 0x00
    cp dragon/disk1.dr ../extra/dragon/disk1.dr
    cp dragon/cmos.dr ../extra/dragon/cmos.dr
fi
